### ISSUE TITLE
“from evoapproxlib import EvoApproxLib” ：ImportError: cannot import name 'EvoApproxLib' from 'evoapproxlib'

### ISSUE THREAD

**Issue by ICE2LAN** [etrommer/agn-approx#5] opened 2023-11-06 01:23 UTC
I can't find the source code for the class EvoApproxLib() in the Multiplier Assignment section of the 1_mnist_ipynb file, could you please help me? Thank you very much.
![image](https://github.com/etrommer/agn-approx/assets/69970740/d7a1154c-8987-4899-bd0e-96cf4c84da56)

**Comment by ICE2LAN** [comment] 2023-11-06 01:25
I have installed version 2022 of the evoapproxlib library.

**Comment by etrommer** [comment] 2023-11-06 16:13
Thank you for pointing this out.

Indeed, the old use case of gradient-based robustness search is not directly supported in torch-approx anymore since my goal is to develop it into a more general approximate computing for ML package. I kept a seperate branch to maintain compatibility, but apparently some breaking changes got accidentally pushed to that branch as well, causing the mismatch you were seeing.

I have pushed fixes on the torch-approx compatibility branch and to the notebook in order to make them functional again. Unfortunately, the approximate retraining is much slower now than it was originally. I'm not entirely sure why. I will double-check on a machine with GPU, as I'm currently only testing on a mobile CPU. Nevertheless, the example should be functional again now. Make sure to reinstall/update agn-approx and dependencies to apply the fixes.

Not that I haven't updated the documentation yet, but you can find the notebook with applied fixes here:
https://github.com/etrommer/agn-approx/blob/main/docs/1_mnist.ipynb

Let me know if you find any other issues!

**Comment by ICE2LAN** [comment] 2023-11-07 01:20
Thank you very much for your reply.

I have successfully run the example program, and recently I have been reading your papers, which are excellent work related to DNN approximation and give me a lot of inspiration.

Thanks again for your open source code, I will try to do some work with your framework.

**Comment by etrommer** [comment] 2023-11-07 08:29
Happy to hear that you are finding it useful!

I try to keep the `main` branches of each repo stable and up-to-date, but things do break from time to time, since I'm actively working on them at the moment. If you work with any tools and encounter errors or unexpected behavior, feel free to open issues for them!

Best of luck for your research!

**Closed as completed by etrommer** 2023-11-07 08:29 UTC
